sudo: required
services:
  - docker

before_install:
  - docker build -t ivanelrey/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ivanelrey/react-test npm test

after_success:
  - docker build -t ivanelrey/multi-client ./client
  - docker build -t ivanelrey/multi-nginx ./nginx
  - docker build -t ivanelrey/multi-server ./server
  - docker build -t ivanelrey/multi-worker ./worker
  # Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ivanelrey/multi-client
  - docker push ivanelrey/multi-nginx
  - docker push ivanelrey/multi-server
  - docker push ivanelrey/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-424541814965
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
